#!/usr/bin/env php

<?php

$name = (string)readline("Your Parter Name: ");

//friendly URL conversion
function to_prety_url($str){
    if($str !== mb_convert_encoding( mb_convert_encoding($str, 'UTF-32', 'UTF-8'), 'UTF-8', 'UTF-32') )
        $str = mb_convert_encoding($str, 'UTF-8', mb_detect_encoding($str));
    $str = htmlentities($str, ENT_NOQUOTES, 'UTF-8');
    $str = preg_replace('`&([a-z]{1,2})(acute|uml|circ|grave|ring|cedil|slash|tilde|caron|lig);`i', '\1', $str);
    $str = html_entity_decode($str, ENT_NOQUOTES, 'UTF-8');
    $str = preg_replace(array('`[^a-z0-9]`i','`[-]+`'), '-', $str);
    $str = strtolower( trim($str, '-') );
    return $str;
}

if($name) {
    if (isset($name[25])) {
        echo "Text is too long. It should be no longer than 25 characters \n";
    } else {
        $user = to_prety_url($name);
        echo "Download Greeting at: http://localhost:6003?name=$user \n";
    }
} else {
    echo "Empty Data \n";
}